IGNORE_INDEX = -100

DEFAULT_COARSE_REFERENCE_START_TOKEN = "<coarse_reference>"
DEFAULT_COARSE_REFERENCE_END_TOKEN = "</coarse_reference>"
DEFAULT_REFERENCE_START_TOKEN = "<reference>"
DEFAULT_REFERENCE_END_TOKEN = "</reference>"
DEFAULT_INSTANCE_START_TOKEN = "<instance>"
DEFAULT_INSTANCE_END_TOKEN = "</instance>"
DEFAULT_ANCHORS_START_TOKEN = "<anchors>"
DEFAULT_ANCHORS_END_TOKEN = "</anchors>"
